use std::collections::HashSet;
use std::path::{Path, PathBuf};

use proc_macro2::Span;
use syn::{Ident, Type, TypePath};

pub struct Symbols {
    internal_module: bool,
    internal_modules: HashSet<PathBuf>,
    consts: HashSet<Ident>,
    funcs: HashSet<Ident>,
    extern_statics: HashSet<Ident>,
    structs: HashSet<Ident>,
    types: HashSet<Ident>,
    primitive_types: HashSet<TypePath>,
    pointer_types: HashSet<TypePath>,
}

impl Symbols {
    pub fn new() -> Symbols {
        fn insert_ident(idents: &mut HashSet<Ident>, sym: &str) {
            idents.insert(Ident::new(sym, Span::call_site()));
        }

        Symbols {
            internal_module: false,
            internal_modules: {
                let mut hs = HashSet::new();
                for s in ["rts/capability.rs"] {
                    hs.insert(PathBuf::from(s));
                }
                hs
            },
            consts: {
                let mut hs = HashSet::new();
                for s in [
                    "BACKTRACE_CHUNK_SZ",
                    "BDESCR_MASK",
                    "BDESCR_SHIFT",
                    "BDESCR_SIZE",
                    "BF_COMPACT",
                    "BF_EVACUATED",
                    "BF_EXEC",
                    "BF_FLAG_MAX",
                    "BF_FRAGMENTED",
                    "BF_KNOWN",
                    "BF_LARGE",
                    "BF_MARKED",
                    "BF_NONMOVING",
                    "BF_NONMOVING_SWEEPING",
                    "BF_PINNED",
                    "BF_SWEPT",
                    "BITMAP_SIZE_MASK",
                    "BITS_PER_BYTE",
                    "BLOCK_MASK",
                    "BLOCK_SHIFT",
                    "DEBUG_IS_ON",
                    "DEFAULT_LINKER_ALWAYS_PIC",
                    "EXIT_DEADLOCK",
                    "EXIT_HEAPOVERFLOW",
                    "EXIT_INTERRUPTED",
                    "EXIT_KILLED",
                    "EventLogStatus_EVENTLOG_NOT_CONFIGURED",
                    "EventLogStatus_EVENTLOG_NOT_SUPPORTED",
                    "EventLogStatus_EVENTLOG_RUNNING",
                    "FMT_HexSizeT",
                    "FMT_HexWord",
                    "FMT_HexWord16",
                    "FMT_HexWord32",
                    "FMT_HexWord64",
                    "FMT_HexWord8",
                    "FMT_Int32",
                    "FMT_Int64",
                    "FMT_SizeT",
                    "FMT_StgThreadID",
                    "FMT_Word16",
                    "FMT_Word64",
                    "FMT_Word8",
                    "GR_FILENAME_FMT",
                    "HP_FILENAME_FMT",
                    "HS_BOOL_FALSE",
                    "HS_BOOL_MAX",
                    "HS_BOOL_MIN",
                    "HS_CHAR_MAX",
                    "HS_CHAR_MIN",
                    "HS_INT16_MAX",
                    "HS_INT16_MIN",
                    "HS_INT32_MAX",
                    "HS_INT32_MIN",
                    "HS_INT8_MAX",
                    "HS_INT8_MIN",
                    "HS_WORD16_MAX",
                    "HS_WORD32_MAX",
                    "HS_WORD8_MAX",
                    "INFO_FIRST_TAG",
                    "INFO_IND_TAG",
                    "INFO_OTHER_TAG",
                    "INVALID_GHC_POINTER",
                    "LDV_LAST_MASK",
                    "LDV_STATE_MASK",
                    "LIFE_FILENAME_FMT",
                    "MAX_NUMA_NODES",
                    "MAX_SPARE_WORKERS",
                    "MAX_SPEC_CONSTR_SIZE",
                    "MAX_SPEC_FUN_SIZE",
                    "MAX_SPEC_THUNK_SIZE",
                    "MBLOCK_MASK",
                    "MBLOCK_SHIFT",
                    "OStatus_OBJECT_DONT_RESOLVE",
                    "OStatus_OBJECT_LOADED",
                    "OStatus_OBJECT_NEEDED",
                    "OStatus_OBJECT_NOT_LOADED",
                    "OStatus_OBJECT_READY",
                    "OStatus_OBJECT_RESOLVED",
                    "OStatus_OBJECT_UNLOADED",
                    "PROF_FILENAME_FMT",
                    "PROF_FILENAME_FMT_GUM",
                    "QP_FILENAME_FMT",
                    "RTS_USER_SIGNALS",
                    "RtsOptsEnabledEnum_RtsOptsAll",
                    "RtsOptsEnabledEnum_RtsOptsIgnore",
                    "RtsOptsEnabledEnum_RtsOptsIgnoreAll",
                    "RtsOptsEnabledEnum_RtsOptsNone",
                    "RtsOptsEnabledEnum_RtsOptsSafeOnly",
                    "SPIN_COUNT",
                    "STACK_SANE",
                    "STATS_FILENAME_MAXLEN",
                    "STAT_FILENAME_FMT",
                    "STG_INT16_MIN",
                    "STG_INT32_MIN",
                    "STG_INT8_MIN",
                    "STG_RETURN",
                    "STG_RUN",
                    "STG_RUN_STACK_FRAME_SIZE",
                    "SchedulerStatus_HeapExhausted",
                    "SchedulerStatus_Interrupted",
                    "SchedulerStatus_Killed",
                    "SchedulerStatus_NoStatus",
                    "SchedulerStatus_Success",
                    "TICKY_FILENAME_FMT",
                    "TIME_FILENAME_FMT",
                    "TIME_FILENAME_FMT_GUM",
                    "TIME_RESOLUTION",
                    "TREC_CHUNK_NUM_ENTRIES",
                    "TRecState_TREC_ABORTED",
                    "TRecState_TREC_ACTIVE",
                    "TRecState_TREC_CONDEMNED",
                    "TRecState_TREC_WAITING",
                    "ThreadYielding",
                    "WORD_SIZE_IN_BITS_FLOAT",
                    "_BTM",
                    "_FRM",
                    "_HNF",
                    "_HPC_READ_FILE",
                    "_HPC_READ_FILE_HPC_NO_EXPLICIT",
                    "_HPC_READ_FILE_HPC_YES_EXPLICIT",
                    "_HPC_READ_FILE_HPC_YES_IMPLICIT",
                    "_IND",
                    "_IO_MANAGER_FLAG_IO_MNGR_FLAG_AUTO",
                    "_IO_MANAGER_FLAG_IO_MNGR_FLAG_MIO",
                    "_IO_MANAGER_FLAG_IO_MNGR_FLAG_SELECT",
                    "_IO_MANAGER_FLAG_IO_MNGR_FLAG_WIN32_LEGACY",
                    "_IO_MANAGER_FLAG_IO_MNGR_FLAG_WINIO",
                    "_MUT",
                    "_NS",
                    "_SRT",
                    "_THU",
                    "_UPT",
                ] {
                    insert_ident(&mut hs, s);
                }
                hs
            },
            funcs: {
                let mut hs = HashSet::new();
                for s in [
                    "__int_encodeFloat",
                    "__word_encodeFloat",
                    "_warnFail",
                    "allocBlockOnNode_lock",
                    "allocBlock_lock",
                    "allocGroup",
                    "allocGroupOnNode",
                    "allocGroupOnNode_lock",
                    "allocMBlockAlignedGroupOnNode",
                    "allocateMightFail",
                    "closeCondition",
                    "closeMutex",
                    "closure_sizeW_",
                    "createAttachedOSThread",
                    "createIOThread",
                    "createStrictIOThread",
                    "dirty_STACK",
                    "dirty_TSO",
                    "eventLogStatus",
                    "exitHpc",
                    "foreignExportStablePtr",
                    "freeAllMBlocks",
                    "freeChain",
                    "freeChain_lock",
                    "freeFullProgArgv",
                    "freeGroup",
                    "freeThreadLocalKey",
                    "freeThreadingResources",
                    "getFirstMBlock",
                    "getMBlock",
                    "getMBlockOnNode",
                    "getMBlocksOnNode",
                    "getNextMBlock",
                    "getStablePtr",
                    "getThreadLocalVar",
                    "ghc_tsan_atomic16_compare_exchange",
                    "ghc_tsan_atomic32_compare_exchange",
                    "ghc_tsan_atomic64_compare_exchange",
                    "ghc_tsan_atomic8_compare_exchange",
                    "heap_view_closurePtrs",
                    "heap_view_closure_ptrs_in_pap_payload",
                    "hs_exit_nowait",
                    "hs_free_fun_ptr",
                    "hs_free_stable_ptr_unsafe",
                    "hs_lock_stable_ptr_table",
                    "hs_lock_stable_tables",
                    "hs_restoreConsoleCP",
                    "hs_set_argv",
                    "hs_unlock_stable_ptr_table",
                    "hs_unlock_stable_tables",
                    "initBlockAllocator",
                    "initMBlocks",
                    "insertSymbol",
                    "interruptOSThread",
                    "joinOSThread",
                    "kernelThreadId",
                    "libdwPrintBacktrace",
                    "listAllBlocks",
                    "newGCdCAF",
                    "newRetainedCAF",
                    "newThreadLocalKey",
                    "osThreadId",
                    "osThreadIsAlive",
                    "releaseThreadNode",
                    "rtsBadAlignmentBarf",
                    "rtsDebugMsgFn",
                    "rtsErrorMsgFn",
                    "rtsFatalInternalErrorFn",
                    "rtsSysErrorMsgFn",
                    "rts_done",
                    "scheduleWaitThread",
                    "setFullProgArgv",
                    "setTSOLink",
                    "setTSOPrev",
                    "setThreadAffinity",
                    "setThreadLocalVar",
                    "setThreadNode",
                    "shutdownHaskell",
                    "signalCondition",
                    "startupHaskell",
                    "startupHpc",
                    "stg_CONTINUATION_apply",
                    "stg_addCFinalizzerToWeakzh",
                    "stg_ap_d_fast",
                    "stg_ap_f_fast",
                    "stg_ap_l_fast",
                    "stg_ap_pppp_fast",
                    "stg_ap_ppppp_fast",
                    "stg_ap_pppppp_fast",
                    "stg_ap_pppv_fast",
                    "stg_ap_ppv_fast",
                    "stg_ap_pv_fast",
                    "stg_ap_stk_v16",
                    "stg_ap_stk_v32",
                    "stg_ap_stk_v64",
                    "stg_ap_v_fast",
                    "stg_atomicModifyMutVar2zh",
                    "stg_atomicModifyMutVarzuzh",
                    "stg_atomicallyzh",
                    "stg_block_blackhole",
                    "stg_block_blackhole_finally",
                    "stg_block_noregs",
                    "stg_block_putmvar",
                    "stg_block_readmvar",
                    "stg_block_stmwait",
                    "stg_block_takemvar",
                    "stg_block_throwto",
                    "stg_casArrayzh",
                    "stg_casInt16Arrayzh",
                    "stg_casInt32Arrayzh",
                    "stg_casInt64Arrayzh",
                    "stg_casInt8Arrayzh",
                    "stg_casIntArrayzh",
                    "stg_casMutVarzh",
                    "stg_casSmallArrayzh",
                    "stg_castDoubleToWord64zh",
                    "stg_castFloatToWord32zh",
                    "stg_castWord32ToFloatzh",
                    "stg_castWord64ToDoublezh",
                    "stg_catchRetryzh",
                    "stg_catchSTMzh",
                    "stg_catchzh",
                    "stg_clearCCSzh",
                    "stg_cloneArrayzh",
                    "stg_cloneMutableArrayzh",
                    "stg_cloneSmallArrayzh",
                    "stg_cloneSmallMutableArrayzh",
                    "stg_closureSizzezh",
                    "stg_compactAddWithSharingzh",
                    "stg_compactAddzh",
                    "stg_compactAllocateBlockzh",
                    "stg_compactAppendzh",
                    "stg_compactContainsAnyzh",
                    "stg_compactContainszh",
                    "stg_compactFixupPointerszh",
                    "stg_compactGetFirstBlockzh",
                    "stg_compactGetNextBlockzh",
                    "stg_compactGetRootzh",
                    "stg_compactNewzh",
                    "stg_compactResizzezh",
                    "stg_compactSizzezh",
                    "stg_control0zh",
                    "stg_control0zh_ll",
                    "stg_copyArrayzh",
                    "stg_copyMutableArrayzh",
                    "stg_copySmallArrayzh",
                    "stg_copySmallMutableArrayzh",
                    "stg_deRefStablePtrzh",
                    "stg_deRefWeakzh",
                    "stg_decodeDoublezu2Intzh",
                    "stg_decodeDoublezuInt64zh",
                    "stg_decodeFloatzuIntzh",
                    "stg_delayzh",
                    "stg_finalizzeWeakzh",
                    "stg_forkOnzh",
                    "stg_forkzh",
                    "stg_freezzeArrayzh",
                    "stg_freezzeSmallArrayzh",
                    "stg_gc_prim",
                    "stg_gc_prim_n",
                    "stg_gc_prim_p",
                    "stg_gc_prim_p_ll",
                    "stg_gc_prim_pp",
                    "stg_gc_prim_pp_ll",
                    "stg_getApStackValzh",
                    "stg_getMaskingStatezh",
                    "stg_getSparkzh",
                    "stg_isByteArrayPinnedzh",
                    "stg_isByteArrayWeaklyPinnedzh",
                    "stg_isCurrentThreadBoundzh",
                    "stg_isEmptyMVarzh",
                    "stg_isMutableByteArrayPinnedzh",
                    "stg_isMutableByteArrayWeaklyPinnedzh",
                    "stg_keepAlivezh",
                    "stg_killMyself",
                    "stg_killThreadzh",
                    "stg_labelThreadzh",
                    "stg_listThreadszh",
                    "stg_makeStableNamezh",
                    "stg_makeStablePtrzh",
                    "stg_maskAsyncExceptionszh",
                    "stg_maskUninterruptiblezh",
                    "stg_mkApUpd0zh",
                    "stg_mkWeakForeignzh",
                    "stg_mkWeakNoFinalizzerzh",
                    "stg_mkWeakzh",
                    "stg_myThreadIdzh",
                    "stg_newAlignedPinnedByteArrayzh",
                    "stg_newArrayzh",
                    "stg_newBCOzh",
                    "stg_newByteArrayzh",
                    "stg_newIOPortzh",
                    "stg_newMVarzh",
                    "stg_newMutVarzh",
                    "stg_newPinnedByteArrayzh",
                    "stg_newPromptTagzh",
                    "stg_newSmallArrayzh",
                    "stg_newTVarzh",
                    "stg_noDuplicatezh",
                    "stg_numSparkszh",
                    "stg_overwritingClosure",
                    "stg_overwritingClosureSize",
                    "stg_overwritingMutableClosureOfs",
                    "stg_promptzh",
                    "stg_putMVarzh",
                    "stg_raiseDivZZerozh",
                    "stg_raiseIOzh",
                    "stg_raiseOverflowzh",
                    "stg_raiseUnderflowzh",
                    "stg_raisezh",
                    "stg_readIOPortzh",
                    "stg_readMVarzh",
                    "stg_readTVarIOzh",
                    "stg_readTVarzh",
                    "stg_resizzeMutableByteArrayzh",
                    "stg_retryzh",
                    "stg_returnToSched",
                    "stg_returnToSchedButFirst",
                    "stg_returnToSchedNotPaused",
                    "stg_runRWzh",
                    "stg_setThreadAllocationCounterzh",
                    "stg_shrinkMutableByteArrayzh",
                    "stg_shrinkSmallMutableArrayzh",
                    "stg_stk_save_v16",
                    "stg_stk_save_v64",
                    "stg_takeMVarzh",
                    "stg_thawArrayzh",
                    "stg_thawSmallArrayzh",
                    "stg_threadFinished",
                    "stg_threadLabelzh",
                    "stg_threadStatuszh",
                    "stg_traceBinaryEventzh",
                    "stg_traceEventzh",
                    "stg_traceMarkerzh",
                    "stg_tryPutMVarzh",
                    "stg_tryReadMVarzh",
                    "stg_tryTakeMVarzh",
                    "stg_unmaskAsyncExceptionszh",
                    "stg_unpackClosurezh",
                    "stg_unsafeThawArrayzh",
                    "stg_unsafeThawSmallArrayzh",
                    "stg_waitReadzh",
                    "stg_waitWritezh",
                    "stg_whereFromzh",
                    "stg_writeIOPortzh",
                    "stg_writeTVarzh",
                    "stg_yield_noregs",
                    "stg_yield_to_interpreter",
                    "stg_yieldzh",
                    "sysErrorBelch",
                    "timedWaitCondition",
                    "vdebugBelch",
                    "verrorBelch",
                    "vsysErrorBelch",
                    "warnMissingKBLibraryPaths",
                    "yieldThread",
                ] {
                    insert_ident(&mut hs, s);
                }
                hs
            },
            extern_statics: {
                let mut hs = HashSet::new();
                for s in [
                    "ALLOC_CON_ctr",
                    "ALLOC_CON_gds",
                    "ALLOC_FUN_ctr",
                    "ALLOC_FUN_gds",
                    "ALLOC_HEAP_ctr",
                    "ALLOC_HEAP_tot",
                    "ALLOC_PAP_ctr",
                    "ALLOC_PAP_gds",
                    "ALLOC_PAP_slp",
                    "ALLOC_PRIM_adm",
                    "ALLOC_PRIM_ctr",
                    "ALLOC_PRIM_gds",
                    "ALLOC_PRIM_slp",
                    "ALLOC_RTS_ctr",
                    "ALLOC_RTS_tot",
                    "ALLOC_SE_THK_ctr",
                    "ALLOC_THK_gds",
                    "ALLOC_THK_slp",
                    "ALLOC_UP_THK_ctr",
                    "ENT_DYN_CON_ctr",
                    "ENT_DYN_THK_MANY_ctr",
                    "ENT_DYN_THK_SINGLE_ctr",
                    "ENT_LNE_ctr",
                    "ENT_STATIC_FUN_DIRECT_ctr",
                    "ENT_STATIC_THK_MANY_ctr",
                    "ENT_STATIC_THK_SINGLE_ctr",
                    "HEAP_CHK_ctr",
                    "KNOWN_CALL_EXTRA_ARGS_ctr",
                    "KNOWN_CALL_TOO_FEW_ARGS_ctr",
                    "KNOWN_CALL_ctr",
                    "MainCapability",
                    "RET_NEW_ctr",
                    "RET_NEW_hst",
                    "RET_OLD_ctr",
                    "RET_OLD_hst",
                    "RET_UNBOXED_TUP_ctr",
                    "RET_UNBOXED_TUP_hst",
                    "RtsFlags",
                    "STK_CHK_ctr",
                    "TAG_TAGGED_pred",
                    "TAG_UNTAGGED_miss",
                    "TAG_UNTAGGED_pred",
                    "UNKNOWN_CALL_ctr",
                    "UPDF_OMITTED_ctr",
                    "UPDF_PUSHED_ctr",
                    "UPD_CAF_BH_SINGLE_ENTRY_ctr",
                    "UPD_CAF_BH_UPDATABLE_ctr",
                    "VERY_SLOW_CALL_ctr",
                    "__stg_EAGER_BLACKHOLE_info",
                    "defaultRtsConfig",
                    "enabled_capabilities",
                    "g0",
                    "generations",
                    "ghc_unique_counter64",
                    "ghc_unique_inc",
                    "keepCAFs",
                    "mblocks_allocated",
                    "n_capabilities",
                    "nonmoving_write_barrier_enabled",
                    "stg_ARR_WORDS_info",
                    "stg_BCO_info",
                    "stg_END_TSO_QUEUE_closure",
                    "stg_IND_STATIC_info",
                    "stg_INTLIKE_closure",
                    "stg_MUT_ARR_PTRS_FROZEN_CLEAN_info",
                    "stg_MUT_ARR_PTRS_FROZEN_DIRTY_info",
                    "stg_PAP_info",
                    "stg_SRT_16_info",
                    "stg_SRT_1_info",
                    "stg_STACK_info",
                    "stg_ap_pp_info",
                    "stg_ap_v_info",
                    "stg_arg_bitmaps",
                    "stg_atomically_frame_info",
                    "stg_bh_upd_frame_info",
                    "stg_catch_frame_info",
                    "stg_catch_retry_frame_info",
                    "stg_catch_stm_frame_info",
                    "stg_ctoi_t3_info",
                    "stg_gc_fun_info",
                    "stg_primcall_info",
                    "stg_restore_cccs_d_info",
                    "stg_restore_cccs_v16_info",
                    "stg_restore_cccs_v32_info",
                    "stg_restore_cccs_v64_info",
                    "stg_ret_n_info",
                    "stg_ret_p_info",
                    "stg_ret_t_info",
                    "stg_stack_underflow_frame_d_info",
                    "stg_stop_thread_info",
                    "stg_unpack_cstring_info",
                    "stg_unpack_cstring_utf8_info",
                    "stg_upd_frame_info",
                ] {
                    insert_ident(&mut hs, s);
                }
                hs
            },
            structs: {
                let mut hs = HashSet::new();
                for s in [
                    "BacktraceChunk_",
                    "Backtrace_",
                    "CapabilityPublic_",
                    "Capability_",
                    "GCDetails_",
                    "InCall_",
                    "InfoProvEnt_",
                    "InfoProv_",
                    "IpeBufferListNode_",
                    "LibdwSession_",
                    "Location_",
                    "MessageBlackHole_",
                    "MessageThrowTo_",
                    "MessageWakeup_",
                    "Message_",
                    "NonmovingSegmentInfo",
                    "PauseToken_",
                    "StgBlockingQueue_",
                    "StgClosureInfo__bindgen_ty_1",
                    "StgClosure_",
                    "StgClosure_",
                    "StgCompactNFDataBlock_",
                    "StgCompactNFData_",
                    "StgConInfoTable_",
                    "StgFunInfoExtraFwd_",
                    "StgFunInfoExtraRev_",
                    "StgFunTable",
                    "StgIndStatic",
                    "StgIntCharlikeClosure",
                    "StgKeepAliveFrame",
                    "StgLargeBitmap_",
                    "StgMVarTSOQueue_",
                    "StgProfInfo",
                    "StgPromptFrame",
                    "StgTRecChunk_",
                    "StgTRecHeader_",
                    "StgTVarWatchQueue_",
                    "StgThunkInfoTable_",
                    "StgThunk_",
                    "StgThunk_",
                    "StgWord128",
                    "StgWord256",
                    "StgWord512",
                    "TRecEntry",
                    "_CONCURRENT_FLAGS",
                    "_COST_CENTRE_FLAGS",
                    "_DEBUG_FLAGS",
                    "_GC_FLAGS",
                    "_HPC_FLAGS",
                    "_HpcModuleInfo",
                    "_MISC_FLAGS",
                    "_ObjectCode",
                    "_PAR_FLAGS",
                    "_PROFILING_FLAGS",
                    "_RTSStats",
                    "_RTS_FLAGS",
                    "_StgCFinalizerList",
                    "_StgEntCounter",
                    "_StgMutArrPtrs",
                    "_StgOrigThunkInfoFrame",
                    "_StgStableName",
                    "_StgUpdateFrame",
                    "_StgWeak",
                    "_TICKY_FLAGS",
                    "_TRACE_FLAGS",
                    "generation_",
                    "generation_",
                    "nursery_",
                ] {
                    insert_ident(&mut hs, s);
                }
                hs
            },
            types: {
                let mut hs = HashSet::new();
                for s in [
                    "AdjustorExecutable",
                    "AdjustorWritable",
                    "CapabilityPublic",
                    "EventLogStatus",
                    "HsFunPtr",
                    "HsPtr",
                    "KernelThreadId",
                    "ListBlocksCb",
                    "ListRootsCb",
                    "ListThreadsCb",
                    "MessageThrowTo",
                    "MessageWakeup",
                    "RtsMsgFunction",
                    "RtsMsgFunctionRetLen",
                    "RtsOptsEnabledEnum",
                    "SchedulerStatus",
                    "StgByteArray",
                    "StgCode",
                    "StgFun",
                    "StgFunPtr",
                    "StgHalfInt",
                    "StgInfoTablePtr",
                    "StgOffset",
                    "StgPromptTag",
                    "StgSRTField",
                    "StgTRecChunk",
                    "StgTSOPtr",
                    "StgThreadID",
                    "StgThreadReturnCode",
                    "StgThunk",
                    "StgThunkInfoTable",
                    "StgVolatilePtr",
                    "StringIdx",
                    "TRecState",
                    "ThreadLocalKey",
                    "_IO_MANAGER_FLAG",
                    "__tsan_atomic16",
                    "__tsan_atomic32",
                    "__tsan_atomic64",
                    "__tsan_atomic8",
                    "memcount",
                ] {
                    insert_ident(&mut hs, s);
                }
                hs
            },
            primitive_types: {
                let mut hs = HashSet::new();
                for s in [
                    "u32",
                    "c",
                    "AdjustorExecutable",
                    "AdjustorWritable",
                    "C_",
                    "F_",
                    "HsBool",
                    "HsChar",
                    "HsDouble",
                    "HsFloat",
                    "HsFunPtr",
                    "HsInt",
                    "HsInt16",
                    "HsInt32",
                    "HsInt64",
                    "HsInt8",
                    "HsPtr",
                    "HsStablePtr",
                    "HsWord",
                    "HsWord16",
                    "HsWord32",
                    "HsWord64",
                    "HsWord8",
                    "I_",
                    "KernelThreadId",
                    "Mutex",
                    "OSThreadId",
                    "OSThreadProc",
                    "P_",
                    "StgAddr",
                    "StgBool",
                    "StgByteArray",
                    "StgChar",
                    "StgCode",
                    "StgDouble",
                    "StgFloat",
                    "StgFun",
                    "StgFunPtr",
                    "StgHalfInt",
                    "StgHalfWord",
                    "StgInt",
                    "StgInt16",
                    "StgInt32",
                    "StgInt64",
                    "StgInt8",
                    "StgOffset",
                    "StgPtr",
                    "StgSRTField",
                    "StgStablePtr",
                    "StgThreadID",
                    "StgThreadReturnCode",
                    "StgVolatilePtr",
                    "StgWord",
                    "StgWord16",
                    "StgWord32",
                    "StgWord64",
                    "StgWord8",
                    "StgWordArray",
                    "StringIdx",
                    "ThreadLocalKey",
                    "Time",
                    "W_",
                    "__tsan_atomic16",
                    "__tsan_atomic32",
                    "__tsan_atomic64",
                    "__tsan_atomic8",
                    "memcount",
                    "pathchar",
                ] {
                    hs.insert(type_path(s));
                }
                hs
            },
            pointer_types: {
                let mut hs = HashSet::new();
                for s in [
                    "AdjustorExecutable",
                    "AdjustorWritable",
                    "HaskellObj",
                    "HsPtr",
                    "HsStablePtr",
                    "ListBlocksCb",
                    "P_",
                    "StgAddr",
                    "StgByteArray",
                    "StgClosurePtr",
                    "StgFun",
                    "StgFunPtr",
                    "StgInfoTablePtr",
                    "StgPromptTag",
                    "StgPtr",
                    "StgStablePtr",
                    "StgTSOPtr",
                    "StgVolatilePtr",
                ] {
                    hs.insert(type_path(s));
                }
                hs
            },
        }
    }

    pub fn with_module(&mut self, path: &Path) {
        self.internal_module = self.internal_modules.contains(path);
    }

    pub fn is_internal_const(&self, ident: &Ident) -> bool {
        self.internal_module || self.consts.contains(ident)
    }

    pub fn is_internal_func(&self, ident: &Ident) -> bool {
        self.internal_module || self.funcs.contains(ident)
    }

    pub fn is_internal_static(&self, ident: &Ident) -> bool {
        self.internal_module || !self.extern_statics.contains(ident)
    }

    pub fn is_internal_struct(&self, ident: &Ident) -> bool {
        self.internal_module || ident.to_string().ends_with("_") || self.structs.contains(ident)
    }

    pub fn is_internal_type(&self, ident: &Ident) -> bool {
        self.internal_module || self.types.contains(ident)
    }

    pub fn is_primitive_type(&self, ty_path: &TypePath) -> bool {
        self.primitive_types.contains(ty_path)
    }

    pub fn is_pointer_type(&self, ty: &Type) -> bool {
        match ty {
            Type::Path(type_path) => self.pointer_types.contains(type_path),
            Type::Ptr(_) => true,
            _ => false,
        }
    }
}

fn type_path(ident: &str) -> TypePath {
    syn::TypePath {
        qself: None,
        path: syn::Path {
            leading_colon: None,
            segments: [syn::PathSegment {
                ident: Ident::new(ident, Span::call_site()),
                arguments: syn::PathArguments::None,
            }]
            .into_iter()
            .collect(),
        },
    }
}
