[formatting]
allowed_blank_lines = 1

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "*-dependencies", "workspace.dependencies"]

[rule.formatting]
reorder_keys = true

[[rule]]
include = ["**/Cargo.toml"]
keys = ["features"]

[rule.formatting]
reorder_arrays = true
