use crate::ffi::rts::storage::info_tables::{_BTM, _FRM, _HNF, _IND, _MUT, _NS, _SRT, _THU, _UPT};
use crate::ffi::stg::types::StgWord16;
use crate::prelude::*;

static mut closure_flags: [StgWord16; 66] = [
    0,
    (_HNF | _NS) as StgWord16,
    (_HNF | _NS) as StgWord16,
    (_HNF | _NS) as StgWord16,
    (_HNF | _NS) as StgWord16,
    (_HNF | _NS) as StgWord16,
    (_HNF | _NS) as StgWord16,
    (_HNF | _NS) as StgWord16,
    (_HNF | _NS | _SRT) as StgWord16,
    (_HNF | _NS | _SRT) as StgWord16,
    (_HNF | _NS | _SRT) as StgWord16,
    (_HNF | _NS | _SRT) as StgWord16,
    (_HNF | _NS | _SRT) as StgWord16,
    (_HNF | _NS | _SRT) as StgWord16,
    (_HNF | _NS | _SRT) as StgWord16,
    (_THU | _SRT) as StgWord16,
    (_THU | _SRT) as StgWord16,
    (_THU | _SRT) as StgWord16,
    (_THU | _SRT) as StgWord16,
    (_THU | _SRT) as StgWord16,
    (_THU | _SRT) as StgWord16,
    (_THU | _SRT) as StgWord16,
    (_THU | _SRT) as StgWord16,
    (_HNF | _NS) as StgWord16,
    (1 << 3) as StgWord16,
    (_HNF | _NS) as StgWord16,
    (1 << 3) as StgWord16,
    (_NS | _IND) as StgWord16,
    (_NS | _IND) as StgWord16,
    (1 << 8) as StgWord16,
    (_BTM | _SRT | _FRM) as StgWord16,
    (_SRT | _FRM) as StgWord16,
    (1 << 8) as StgWord16,
    (_BTM | _FRM) as StgWord16,
    (_BTM | _FRM) as StgWord16,
    (_BTM | _FRM) as StgWord16,
    (_BTM | _FRM) as StgWord16,
    (_NS | _MUT | _UPT) as StgWord16,
    (_NS | _UPT) as StgWord16,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_HNF | _NS | _UPT) as StgWord16,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_HNF | _NS | _UPT) as StgWord16,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_HNF | _NS | _UPT) as StgWord16,
    (_HNF | _NS | _UPT) as StgWord16,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_NS | _MUT | _UPT) as StgWord16,
    (_BTM | _FRM) as StgWord16,
    (_BTM | _FRM) as StgWord16,
    (_BTM | _FRM) as StgWord16,
    0,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_HNF | _NS | _MUT | _UPT) as StgWord16,
    (_HNF | _NS | _UPT) as StgWord16,
    (_HNF | _NS) as StgWord16,
    (_HNF | _NS | _UPT) as StgWord16,
    (_BTM | _FRM) as StgWord16,
];
