#!/usr/bin/env bash
set -eo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

_files=(
  # rts/src/ffi/hs_ffi.rs
  # rts/src/ffi/hs_ffi/tests.rs
  # rts/src/ffi/mach_deps.rs
  # rts/src/ffi/mach_deps/tests.rs
  # rts/src/ffi/rts/prof/ccs.rs
  # rts/src/ffi/rts/prof/ccs/tests.rs
  # rts/src/ffi/rts/storage/block.rs
  # rts/src/ffi/rts/storage/block/tests.rs
  # rts/src/ffi/rts/storage/gc.rs
  # rts/src/ffi/rts/storage/gc/tests.rs
  # rts/src/ffi/rts/storage/info_tables.rs
  # rts/src/ffi/rts/storage/info_tables/tests.rs
  # rts/src/ffi/rts/storage/tso.rs
  # rts/src/ffi/rts/storage/tso/tests.rs
  # rts/src/ffi/rts.rs
  # rts/src/ffi/rts/tests.rs
  # rts/src/ffi/stg/regs.rs
  # rts/src/ffi/stg/regs/tests.rs
  # rts/src/ffi/rts/adjustor/tests.rs
  # rts/src/ffi/rts/adjustor.rs
  # rts/src/ffi/rts/block_signals/tests.rs
  # rts/src/ffi/rts/block_signals.rs
  # rts/src/ffi/rts/config/tests.rs
  # rts/src/ffi/rts/config.rs
  # rts/src/ffi/rts/constants/tests.rs
  # rts/src/ffi/rts/constants.rs
  # rts/src/ffi/rts/event_log_writer/tests.rs
  # rts/src/ffi/rts/event_log_writer.rs
  # rts/src/ffi/rts/exec_page/tests.rs
  # rts/src/ffi/rts/exec_page.rs
  # rts/src/ffi/rts/file_lock/tests.rs
  # rts/src/ffi/rts/file_lock.rs
  # rts/src/ffi/rts/flags/tests.rs
  # rts/src/ffi/rts/flags.rs
  # rts/src/ffi/rts/foreign_exports/tests.rs
  # rts/src/ffi/rts/foreign_exports.rs
  # rts/src/ffi/rts/get_time/tests.rs
  # rts/src/ffi/rts/get_time.rs
  # rts/src/ffi/rts/globals/tests.rs
  # rts/src/ffi/rts/globals.rs
  # rts/src/ffi/rts/hpc/tests.rs
  # rts/src/ffi/rts/hpc.rs
  # rts/src/ffi/rts/io_interface/tests.rs
  # rts/src/ffi/rts/io_interface.rs
  # rts/src/ffi/rts/ipe/tests.rs
  # rts/src/ffi/rts/ipe.rs
  # rts/src/ffi/rts/libdw/tests.rs
  # rts/src/ffi/rts/libdw.rs
  # rts/src/ffi/rts/libdw_pool/tests.rs
  # rts/src/ffi/rts/libdw_pool.rs
  # rts/src/ffi/rts/linker/tests.rs
  # rts/src/ffi/rts/linker.rs
  # rts/src/ffi/rts/main/tests.rs
  # rts/src/ffi/rts/main.rs
  # rts/src/ffi/rts/messages.rs
  # rts/src/ffi/rts/non_moving/tests.rs
  # rts/src/ffi/rts/non_moving.rs
  # rts/src/ffi/rts/os_threads/tests.rs
  # rts/src/ffi/rts/os_threads.rs
  # rts/src/ffi/rts/parallel/tests.rs
  # rts/src/ffi/rts/parallel.rs
  # rts/src/ffi/rts/prim_float/tests.rs
  # rts/src/ffi/rts/prim_float.rs
  # rts/src/ffi/rts/prof/heap/tests.rs
  # rts/src/ffi/rts/prof/heap.rs
  # rts/src/ffi/rts/profiling/tests.rs
  # rts/src/ffi/rts/profiling.rs
  # rts/src/ffi/rts/rts_to_hs_iface.rs
  # rts/src/ffi/rts/rts_to_hs_iface/tests.rs
  # rts/src/ffi/rts/signals/tests.rs
  # rts/src/ffi/rts/signals.rs
  # rts/src/ffi/rts/stable_name/tests.rs
  # rts/src/ffi/rts/stable_name.rs
  # rts/src/ffi/rts/stable_ptr/tests.rs
  # rts/src/ffi/rts/stable_ptr.rs
  # rts/src/ffi/rts/static_ptr_table/tests.rs
  # rts/src/ffi/rts/static_ptr_table.rs
  # rts/src/ffi/rts/storage/closure_macros/tests.rs
  # rts/src/ffi/rts/storage/closure_macros.rs
  # rts/src/ffi/rts/storage/closure_types/tests.rs
  # rts/src/ffi/rts/storage/closure_types.rs
  # rts/src/ffi/rts/storage/closures/tests.rs
  # rts/src/ffi/rts/storage/closures.rs
  # rts/src/ffi/rts/storage/fun_types/tests.rs
  # rts/src/ffi/rts/storage/fun_types.rs
  # rts/src/ffi/rts/storage/heap/tests.rs
  # rts/src/ffi/rts/storage/heap.rs
  # rts/src/ffi/rts/storage/m_block/tests.rs
  # rts/src/ffi/rts/storage/m_block.rs
  # rts/src/ffi/rts/threads/tests.rs
  # rts/src/ffi/rts/threads.rs
  # rts/src/ffi/rts/ticky/tests.rs
  # rts/src/ffi/rts/ticky.rs
  # rts/src/ffi/rts/time/tests.rs
  # rts/src/ffi/rts/time.rs
  # rts/src/ffi/rts/timer/tests.rs
  # rts/src/ffi/rts/timer.rs
  # rts/src/ffi/rts/tsan_utils/tests.rs
  # rts/src/ffi/rts/tsan_utils.rs
  # rts/src/ffi/rts/tty/tests.rs
  # rts/src/ffi/rts/tty.rs
  # rts/src/ffi/rts/utils/tests.rs
  # rts/src/ffi/rts/utils.rs
  # rts/src/ffi/rts_api/tests.rs
  # rts/src/ffi/rts_api.rs
  # rts/src/ffi/stg.rs
  # rts/src/ffi/stg/tests.rs
  # rts/src/ffi/stg/mach_regs_for_host.rs
  # rts/src/ffi/stg/mach_regs_for_host/tests.rs
  # rts/src/ffi/stg/misc_closures/tests.rs
  # rts/src/ffi/stg/misc_closures.rs
  # rts/src/ffi/stg/prim/tests.rs
  # rts/src/ffi/stg/prim.rs
  # rts/src/ffi/stg/smp/tests.rs
  # rts/src/ffi/stg/smp.rs
  # rts/src/ffi/stg/ticky/tests.rs
  # rts/src/ffi/stg/ticky.rs
  # rts/src/ffi/stg/types.rs
  # rts/src/ffi/stg/types/tests.rs
)

if [[ $# -gt 0 ]]; then
  _files=("$@")
fi

rm -f "${_files[@]}"

cargo run -p generate-ffi rts/src/ffi

sed -i \
  -e 's/::core::option:://g' \
  -e 's/::core::ffi:://g' \
  -e 's/::core::mem:://g' \
  -e 's/::core::slice::/slice::/g' \
  "${_files[@]}"

treefmt -q "${_files[@]}"
