#!/usr/bin/env bash
set -eo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

_files=(
  # Modified
  ghc-rts/src/hs_ffi/tests.rs
  ghc-rts/src/rts/capability.rs
  ghc-rts/src/rts/capability/tests.rs
  ghc-rts/src/rts/prof/ccs.rs
  ghc-rts/src/rts/prof/ccs/tests.rs
  ghc-rts/src/rts/storage/block.rs
  ghc-rts/src/rts/storage/block/tests.rs
  ghc-rts/src/rts/storage/gc/tests.rs
  ghc-rts/src/rts/storage/info_tables.rs
  ghc-rts/src/rts/storage/info_tables/tests.rs
  ghc-rts/src/rts/types.rs
  ghc-rts/src/rts/types/tests.rs
  ghc-rts/src/stg/regs.rs
  ghc-rts/src/stg/regs/tests.rs
  # Generated
  ghc-rts/src/rts/adjustor/tests.rs
  ghc-rts/src/rts/adjustor.rs
  ghc-rts/src/rts/block_signals/tests.rs
  ghc-rts/src/rts/block_signals.rs
  ghc-rts/src/rts/config/tests.rs
  ghc-rts/src/rts/config.rs
  ghc-rts/src/rts/constants/tests.rs
  ghc-rts/src/rts/constants.rs
  ghc-rts/src/rts/event_log_writer/tests.rs
  ghc-rts/src/rts/event_log_writer.rs
  ghc-rts/src/rts/exec_page/tests.rs
  ghc-rts/src/rts/exec_page.rs
  ghc-rts/src/rts/file_lock/tests.rs
  ghc-rts/src/rts/file_lock.rs
  ghc-rts/src/rts/flags/tests.rs
  ghc-rts/src/rts/flags.rs
  ghc-rts/src/rts/foreign_exports/tests.rs
  ghc-rts/src/rts/foreign_exports.rs
  ghc-rts/src/rts/get_time/tests.rs
  ghc-rts/src/rts/get_time.rs
  ghc-rts/src/rts/globals/tests.rs
  ghc-rts/src/rts/globals.rs
  ghc-rts/src/rts/hpc/tests.rs
  ghc-rts/src/rts/hpc.rs
  ghc-rts/src/rts/io_interface/tests.rs
  ghc-rts/src/rts/io_interface.rs
  ghc-rts/src/rts/ipe/tests.rs
  ghc-rts/src/rts/ipe.rs
  ghc-rts/src/rts/libdw/tests.rs
  ghc-rts/src/rts/libdw.rs
  ghc-rts/src/rts/libdw_pool/tests.rs
  ghc-rts/src/rts/libdw_pool.rs
  ghc-rts/src/rts/linker/tests.rs
  ghc-rts/src/rts/linker.rs
  ghc-rts/src/rts/main/tests.rs
  ghc-rts/src/rts/main.rs
  ghc-rts/src/rts/messages/tests.rs
  ghc-rts/src/rts/messages.rs
  ghc-rts/src/rts/non_moving/tests.rs
  ghc-rts/src/rts/non_moving.rs
  ghc-rts/src/rts/os_threads/tests.rs
  ghc-rts/src/rts/os_threads.rs
  ghc-rts/src/rts/parallel/tests.rs
  ghc-rts/src/rts/parallel.rs
  ghc-rts/src/rts/prim_float/tests.rs
  ghc-rts/src/rts/prim_float.rs
  ghc-rts/src/rts/prof/heap/tests.rs
  ghc-rts/src/rts/prof/heap.rs
  ghc-rts/src/rts/prof/ldv/tests.rs
  ghc-rts/src/rts/prof/ldv.rs
  ghc-rts/src/rts/profiling/tests.rs
  ghc-rts/src/rts/profiling.rs
  ghc-rts/src/rts/signals/tests.rs
  ghc-rts/src/rts/signals.rs
  ghc-rts/src/rts/spin_lock/tests.rs
  ghc-rts/src/rts/spin_lock.rs
  ghc-rts/src/rts/stable_name/tests.rs
  ghc-rts/src/rts/stable_name.rs
  ghc-rts/src/rts/stable_ptr/tests.rs
  ghc-rts/src/rts/stable_ptr.rs
  ghc-rts/src/rts/static_ptr_table/tests.rs
  ghc-rts/src/rts/static_ptr_table.rs
  ghc-rts/src/rts/storage/closure_macros/tests.rs
  ghc-rts/src/rts/storage/closure_macros.rs
  ghc-rts/src/rts/storage/closure_types/tests.rs
  ghc-rts/src/rts/storage/closure_types.rs
  ghc-rts/src/rts/storage/closures/tests.rs
  ghc-rts/src/rts/storage/closures.rs
  ghc-rts/src/rts/storage/fun_types/tests.rs
  ghc-rts/src/rts/storage/fun_types.rs
  ghc-rts/src/rts/storage/heap/tests.rs
  ghc-rts/src/rts/storage/heap.rs
  ghc-rts/src/rts/storage/m_block/tests.rs
  ghc-rts/src/rts/storage/m_block.rs
  ghc-rts/src/rts/threads/tests.rs
  ghc-rts/src/rts/threads.rs
  ghc-rts/src/rts/ticky/tests.rs
  ghc-rts/src/rts/ticky.rs
  ghc-rts/src/rts/time/tests.rs
  ghc-rts/src/rts/time.rs
  ghc-rts/src/rts/timer/tests.rs
  ghc-rts/src/rts/timer.rs
  ghc-rts/src/rts/tsan_utils/tests.rs
  ghc-rts/src/rts/tsan_utils.rs
  ghc-rts/src/rts/tty/tests.rs
  ghc-rts/src/rts/tty.rs
  ghc-rts/src/rts/utils/tests.rs
  ghc-rts/src/rts/utils.rs
  ghc-rts/src/rts_api/tests.rs
  ghc-rts/src/rts_api.rs
  ghc-rts/src/stg/dll/tests.rs
  ghc-rts/src/stg/dll.rs
  ghc-rts/src/stg/misc_closures/tests.rs
  ghc-rts/src/stg/misc_closures.rs
  ghc-rts/src/stg/prim/tests.rs
  ghc-rts/src/stg/prim.rs
  ghc-rts/src/stg/smp/tests.rs
  ghc-rts/src/stg/smp.rs
  ghc-rts/src/stg/tests.rs
  ghc-rts/src/stg/ticky/tests.rs
  ghc-rts/src/stg/ticky.rs
)

rm -f "${_files[@]}"

cargo run -p generate ghc-rts/src

sed -i \
  -e 's/::core::option:://g' \
  -e 's/::core::ffi:://g' \
  -e 's/::core::slice::/slice::/g' \
  "${_files[@]}"
