use crate::ffi::stg::types::{StgWord, StgWord64};
use crate::prelude::*;

#[cfg(test)]
mod tests;

static mut popcount_tab: [c_uchar; 256] = [
    0 as c_int as c_uchar,
    1 as c_int as c_uchar,
    1 as c_int as c_uchar,
    2 as c_int as c_uchar,
    1 as c_int as c_uchar,
    2 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    1 as c_int as c_uchar,
    2 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    1 as c_int as c_uchar,
    2 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    1 as c_int as c_uchar,
    2 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    1 as c_int as c_uchar,
    2 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    6 as c_int as c_uchar,
    7 as c_int as c_uchar,
    1 as c_int as c_uchar,
    2 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    6 as c_int as c_uchar,
    7 as c_int as c_uchar,
    2 as c_int as c_uchar,
    3 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    6 as c_int as c_uchar,
    7 as c_int as c_uchar,
    3 as c_int as c_uchar,
    4 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    6 as c_int as c_uchar,
    7 as c_int as c_uchar,
    4 as c_int as c_uchar,
    5 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    6 as c_int as c_uchar,
    7 as c_int as c_uchar,
    5 as c_int as c_uchar,
    6 as c_int as c_uchar,
    6 as c_int as c_uchar,
    7 as c_int as c_uchar,
    6 as c_int as c_uchar,
    7 as c_int as c_uchar,
    7 as c_int as c_uchar,
    8 as c_int as c_uchar,
];

#[ffi(compiler)]
#[unsafe(no_mangle)]
#[instrument]
pub unsafe extern "C" fn hs_popcnt8(mut x: StgWord) -> StgWord {
    return popcount_tab[x as c_uchar as usize] as StgWord;
}

#[ffi(compiler)]
#[unsafe(no_mangle)]
#[instrument]
pub unsafe extern "C" fn hs_popcnt16(mut x: StgWord) -> StgWord {
    return (popcount_tab[x as c_uchar as usize] as c_int
        + popcount_tab[(x >> 8 as c_int) as c_uchar as usize] as c_int) as StgWord;
}

#[ffi(compiler)]
#[unsafe(no_mangle)]
#[instrument]
pub unsafe extern "C" fn hs_popcnt32(mut x: StgWord) -> StgWord {
    return (popcount_tab[x as c_uchar as usize] as c_int
        + popcount_tab[(x >> 8 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 16 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 24 as c_int) as c_uchar as usize] as c_int) as StgWord;
}

#[ffi(compiler)]
#[unsafe(no_mangle)]
#[instrument]
pub unsafe extern "C" fn hs_popcnt64(mut x: StgWord64) -> StgWord {
    return (popcount_tab[x as c_uchar as usize] as c_int
        + popcount_tab[(x >> 8 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 16 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 24 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 32 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 40 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 48 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 56 as c_int) as c_uchar as usize] as c_int) as StgWord;
}

#[ffi(compiler)]
#[unsafe(no_mangle)]
#[instrument]
pub unsafe extern "C" fn hs_popcnt(mut x: StgWord) -> StgWord {
    return (popcount_tab[x as c_uchar as usize] as c_int
        + popcount_tab[(x >> 8 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 16 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 24 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 32 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 40 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 48 as c_int) as c_uchar as usize] as c_int
        + popcount_tab[(x >> 56 as c_int) as c_uchar as usize] as c_int) as StgWord;
}
