[package]
name = "ghc-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
proc-macro = true

[features]
tracing = []

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
